\getenv app_password APP_DB_PASSWORD
CREATE ROLE convexa LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
ALTER DATABASE convexa OWNER TO convexa;
ALTER SCHEMA public OWNER TO convexa;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
